# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
early_access: true
enable_free_tier: false
reviews:
  collapse_walkthrough: true
  sequence_diagrams: false
  poem: false
  path_filters:
    - '!collection-zendly/**'
